### ISSUE TITLE
RAW file Format

### ISSUE THREAD

**Issue by AlexKimov** [AlexKimov/HardTruck-RignRoll-file-formats#8]
- [x] File format description
- [x] Structure

**Comment by zheka20012** [comment]
Не уверен по поводу правильности описания, там скорее всего 2 байта а 1 unsigned short int, в итоге это 16-битное изображение в градациях серого, которое можно открыть в том же фотошопе
![image](https://user-images.githubusercontent.com/15785537/114926235-c70ff100-9e38-11eb-9d79-72696eeac364.png)
![image](https://user-images.githubusercontent.com/15785537/114926315-e0b13880-9e38-11eb-9cb1-90b7e2bc64d0.png)

**Comment by AlexKimov** [comment]
@zheka20012 Все верно. Разницы не будет, можно по одному байту брать для построения, можно сразу по два считать. В первом случае возможные значения будут лежать в диапазоне 0...255 и первый байт равен второму, третий - четвертому и т.д.,  во втором 0, 257, 514... 65535. В общем случае это именно изображение, больше информации есть здесь https://vk.com/db_games?w=wall-11599748_48671 .

**Comment by AlexKimov** [comment]
> Не уверен по поводу правильности описания

Описание далеко от идеального и нужно его переделывать, если есть предложения и желание участвовать, можно сделать лучше.
